name: easycut
description: A new Flutter project.
publish_to: 'none'
version: 1.0.4+4
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.3.0
  cloud_firestore: ^4.17.5
  connectivity_plus: ^6.0.5
  country_list: ^0.0.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dots_indicator: ^3.0.0
  dropdown_button2: ^2.1.4
  firebase_core: ^2.24.2
  firebase_messaging: ^14.9.4
  flutter:
    sdk: flutter
  flutter_exit_app: ^1.1.3
  flutter_local_notifications: ^17.2.1
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_timezone: ^3.0.0
  get: ^4.6.1
  http: ^0.13.6
  image_picker: ^1.0.4
  intl: ^0.18.1
  logger: ^2.1.0
  lottie: ^2.3.2
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.0
  syncfusion_flutter_datepicker: ^28.1.41
  timezone: ^0.9.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
    - assets/images/salonbk/
    - assets/images/icon/
    - assets/countries/countries.json

  fonts:
    - family: Calligraffitti
      fonts:
        - asset: assets/fonts/static/Calligraffitti-Regular.ttf
          weight: 400


    - family: Cairo
      fonts:
        - asset: assets/fonts/static/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Cairo-SemiBold.ttf
          weight: 600
