# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :Publish do
    sh "flutter clean"
    sh "flutter build apk --release --no-tree-shake-icons"
    firebase_app_distribution(
            app: "1:372013397182:android:e2f10ddfb40448a1b01aef",
            firebase_cli_token:"1//03-BdQp9Qs9tjCgYIARAAGAMSNwF-L9IrTya2Qthj6nPkNd031wKe5WipHT3t4yVRfbmrqOCjCsCe3Vpgs919X1fUVsWgn38nhqA",
            android_artifact_type:"APK",
            android_artifact_path:"../build/app/outputs/flutter-apk/app-release.apk", 
            testers: "tester1@company.com, tester2@company.com",
            release_notes: "Lots of amazing new features to test out!"
        )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
