Map<String, String> langDe = {
  'chooseLanguage': 'Sprache wählen',
  'arabic': 'Arabisch',
  'english': 'Englisch',
  'german': 'Deutsch',
  'easyCut': 'Einfacher Schnitt',
  'startWithUs':
      'Der Einstieg bei uns ist sehr einfach \nWir sparen deine Zeit',
  'bookingNow': 'Jetzt buchen',
  'bookAnyTime':
      'Buche jederzeit. \nWir bedienen den nächstgelegenen Salon für dich.',
  'trackReceipt': 'Rechnung verfolgen',
  'accessPayments':
      'Du kannst jetzt auf deine Zahlungen zugreifen \nund Produkte kaufen.',
  'listProducts': 'Produktliste',
  'buyProducts': 'Du kannst jedes Produkt \n aus deinem Salon kaufen.',
  'continue': 'Weiter',
  'welcome': 'Willkommen',
  'happyToSeeYou': 'Schön, dich zu sehen,',
  'loginNow': 'Jetzt einloggen und Zeit sparen.',
  'email': 'E-Mail',
  'password': 'Passwort',
  'forgetPassword': 'Passwort vergessen?',
  'login': 'Einloggen',
  'dontHaveAccount': 'Du hast noch keinen Account?',
  'register': 'Registrieren',
  'resetPassword': 'Passwort zurücksetzen',
  'congratulation': 'Herzlichen Glückwunsch',
  'enterNewPassword': 'Bitte neues Passwort eingeben',
  'reEnterPassword': 'Passwort erneut eingeben',
  'goToLogin': 'Zum Einloggen gehen',
  'fullName': 'Vollständiger Name',
  'phoneNumber': 'Telefonnummer',
  'haveAnAccount': 'Hast du einen Account?',
  'gender': 'Geschlecht',
  'male': 'Männlich',
  'female': 'Weiblich',
  'nameNotValid': 'Name ungültig',
  'emailNotValid': 'E-Mail ungültig',
  'phoneNotValid': 'Telefonnummer ungültig',
  'requiredField':
      'Dieses Feld ist erforderlich, um auf die Daten basierend auf Ihren Informationen zuzugreifen',
  'cantBeLessThan': 'Darf nicht weniger als sein',
  'cantBeGreaterThan': 'Darf nicht größer als sein',
  'alert': 'Warnung!',
  'exitApp': 'Möchten Sie die App verlassen?',
  'yes': 'Ja',
  'no': 'Nein',
  'Your salon is on your phone': 'Ihr Salon ist auf Ihrem Handy',
  'Near for you': 'Für Sie in Ihrer Nähe',
  'Don’t waste your time and book at your preference':
      'Verschwenden Sie keine Zeit und buchen Sie nach Ihren Wünschen',
  'Newest Salons': 'Neueste Salons',
  'Please login first to choose among various barbers in your location':
      'Bitte loggen Sie sich zuerst ein, um zwischen verschiedenen Friseuren in Ihrem Standort zu wählen',
  'Hello': 'Hallo',
  'All Bookings': 'Alle Buchungen',
  'No bookings available': 'Keine Buchungen möglich',
  'Salon Name:': 'Name des Salons:',
  'username': 'Nutzername:',
  'Salon Phone:': 'Salon-Telefon:',
  'Day': 'Tag',
  'Time:': 'Zeit:',
  'Total:': 'Gesamt:',
  'Status:': 'Status:',
  'Delete Account': 'Konto löschen',
  'About': 'Über',
  'Favorites': 'Favoriten',
  'Home': 'Heim',
  'Booking': 'Buchung',
  'Profile': 'Profil',
  'Are you sure want to exit the app?':
      'Sind Sie sicher, dass Sie die App beenden möchten?',
  'Country': 'Land',
  'Select State': 'Bundesland auswählen',
  'Please select State': 'Bitte wählen Sie ein Bundesland',
  'Select City': 'Stadt auswählen',
  'Please select City': 'Bitte wählen Sie Stadt',
  'Select Image': 'Bild auswählen',
  'Email is required': 'E-Mail ist erforderlich',
  'Please enter a valid Gmail address':
      'Bitte geben Sie eine gültige Gmail-Adresse ein.',
  'enter your mail please!': 'Geben Sie bitte Ihre E-Mail-Adresse ein!',
  'check your mail': 'Überprüfen Sie Ihre E-Mails',
  'Congratulation': 'Gratulation',
  'You information is correct \nWait for loading Data.':
      'Ihre Informationen sind korrekt Warten Sie, bis die Daten geladen sind.',
  'Your verify code is correct': 'Ihr Überprüfungscode ist korrekt',
  'Your code is incorrect': 'Ihr Code ist falsch',
  'Warning': 'Warnung',
  'Success': 'Erfolg',
  'Congratulations, PIN is correct!':
      'Herzlichen Glückwunsch, PIN ist korrekt!',
  'Error': 'Fehler',
  'The PIN you entered is incorrect. Try again.':
      'Die von Ihnen eingegebene PIN ist falsch. Wiederholen.',
  'Please, choose a date': 'Bitte wählen Sie ein Datum',
  '"Please, choose a time"': '"Bitte wählen Sie eine Uhrzeit"',
  'Please, choose at least one service':
      'Bitte wählen Sie mindestens eine Dienstleistung aus',
  'Booking Successful': 'Buchung erfolgreich',
  'Please wait until the salon accepts your booking':
      'Bitte warten Sie, bis der Salon Ihre Buchung akzeptiert',
  'Booking Error': 'Buchungsfehler',
  'You already have a booking at this time. Please choose a different time or date.':
      'Sie haben zu diesem Zeitpunkt bereits eine Buchung. Bitte wählen Sie eine andere Uhrzeit oder ein anderes Datum.',
  'Your information is incorrect': 'Ihre Angaben sind falsch',
  'Booking Now': 'Jetzt buchen',
  'Booking Details': 'Buchungsdetails',
  'Back to Home': 'Zurück zur Startseite',
  'Your Booking is still not accepted, \n':
      'Ihre Buchung wurde immer noch nicht akzeptiert',
  'You must upload image for your Profile':
      'Sie müssen ein Bild für Ihr Profil hochladen',
  'Register Success': 'Erfolgreich registriert',
  'Your Register is successfully.Go to your account to get verify code':
      'Ihre Registrierung war erfolgreich. Gehen Sie zu Ihrem Konto, um den Bestätigungscode abzurufen.',
  'user_name': 'Nutzer name',
  'Create an Account to Show your profile':
      'Erstellen Sie ein Konto, um Ihr Profil anzuzeigen',
  'To view or make bookings, you need to create an account and log in.':
      'Um Buchungen anzuzeigen oder vorzunehmen, müssen Sie ein Konto erstellen und sich anmelden.',
  'Create an Account to Access Bookings':
      'Erstellen Sie ein Konto, um auf Buchungen zuzugreifen',
  'To view , you need to create an account and log in.':
      'Zum Anzeigen müssen Sie ein Konto erstellen und sich anmelden.',
  'Submit': 'Einreichen',
  'Choose Services': 'Wählen Sie Dienste',
  'Choose': 'Wählen',
  'Choose Time': 'Wähle Zeit',
  'Choose Date': 'Datum wählen',
  'Chair': 'Stuhl',
  'Choose Chair': 'Stuhl auswählen',
  'Name': 'Name',
  'Book Now': 'Jetzt buchen',
  'Salon Name': 'Name des Salons',
  'Date': 'Datum',
  'Time': 'Zeit',
  'Duplicate Booking': 'Doppelte Buchung',
  'is already booked at this time. Please choose a different chair, time, or date.':
      'ist zu diesem Zeitpunkt bereits ausgebucht. Bitte wählen Sie einen anderen Stuhl, eine andere Uhrzeit oder ein anderes Datum.',
  'Failed to save booking to API backend':
      'Buchung konnte nicht im API-Backend gespeichert werden',
  'Booking submission failed': 'Buchungsübermittlung fehlgeschlagen',
  'Added to your Favorites': 'Zu Ihren Favoriten hinzugefügt',
  'There is no data': 'Es liegen keine Daten vor',
  'Removed from your Favorites': 'Aus Ihren Favoriten entfernt',
  'Services': 'Dienstleistungen',
  'Products': 'Produkte',
  'Price:': 'Preis:',
  'Number:': 'Nummer:',
  'Please check your internet connection':
      'Bitte überprüfen Sie Ihre Internetverbindung',
  'Address': 'Adresse',
  'Logout': 'Ausloggen',
  'Waiting': 'Warten',
  'Accepted': 'Akzeptiert',
  'Refused': 'Abgelehnt',
  'Exit': 'xit',
  'Booking Approved': 'Buchung bestätigt',
  'Your booking has been approved!': 'Ihre Buchung wurde genehmigt!',
  'Booking Refused': 'Buchung abgelehnt',
  'Your booking has been refused.': 'Ihre Buchung wurde abgelehnt.',
  'No salons available.': 'Keine Salons verfügbar.',
  'Are you sure to delete your account?':
      'Möchten Sie Ihr Konto wirklich löschen?',
  'Failed to Delete Account, Try Again':
      'Konto konnte nicht gelöscht werden. Versuchen Sie es erneut.',
  'There is no data for your country': 'Für Ihr Land liegen keine Daten vor',
  'An error occurred while fetching data.':
      'Beim Abrufen der Daten ist ein Fehler aufgetreten.',
  'Action failed.': 'Aktion fehlgeschlagen.',
  'Failed to perform action. Please try again.':
      'Aktion konnte nicht ausgeführt werden. Bitte versuchen Sie es erneut.',
  'No data available': 'Keine Daten verfügbar',
  'Failed to load data. Please try again.':
      'Feld-Taha-Ladedaten. Bitte versuchen Sie es mit Teig.',
  'Email Already Exists': 'E-Mail existiert bereits',
  'egypt': 'مصر',
  'Email Found': 'E-Mail gefunden',
  'Please, Check your Account,We sent Verification code':
      'Bitte überprüfen Sie Ihr Konto. Wir haben einen Bestätigungscode gesendet.',
  'Email is not found': 'E-Mail wurde nicht gefunden',
  'Password Change Successfully': 'Passwort erfolgreich geändert',
  'please choose a Strong Password': 'Bitte wählen Sie ein sicheres Passwort',
  'New Password is not Equal to Confirm Password':
      'Neues Passwort ist nicht gleich Passwort bestätigen',
  'Login Required': 'Anmeldung erforderlich',
  'You need to log in to continue. Do you want to log in?':
      'Sie müssen sich anmelden, um fortzufahren. Möchten Sie sich einloggen?',
  'Log In': 'Anmelden',
  'Cancel': 'Abbrechen',
  'Please, Enter the verification code':
      'Bitte geben Sie den Bestätigungscode ein',
  'Please, fill in the form': 'Bitte füllen Sie das Formular aus',
  'View Products': 'Produkte anzeigen',
  'Now you can buy products sold in the salon and add them to your bill':
      'Jetzt können Sie im Salon verkaufte Produkte kaufen und Ihrer Rechnung hinzufügen',
  'Track invoice': 'Rechnung verfolgen',
  'You can see how much your haircut will cost. Also, if you want to buy a product':
      'Sie können sehen, wie viel Ihr Haarschnitt kosten wird. Auch wenn Sie ein Produkt kaufen möchten',
  'Now you can book at any time. We also provide you with the nearest salons to you':
      'Jetzt können Sie jederzeit buchen. Wir bieten Ihnen auch die nächstgelegenen Salons an',
  'Your start will be easier because we will save your time':
      'Ihr Start wird einfacher, weil wir Ihnen Zeit sparen',
  'Rating successfully': 'Rating successfully',
  'Total Price': 'Totale Pause',
  'Total Time': 'Gesamtteam',
  'Start Time': 'Startteam',
  'min': 'Min',
  'PM': 'PM',
  'AM': 'AM',
  'Men': 'Men',
  'Women': 'Women',
  'Search': 'Suchen',
  'Sorry': 'Tut mir Leid',
  'Salon is closed on this date': 'Der Salon ist an diesem Tag geschlossen',
  'Connection error': 'Verbindungsfehler',
  'Search for a Salon or nearest city...':
      'Suchen Sie nach einem Salon oder der nächstgelegenen Stadt ...',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
};
