Map<String, String> langEn = {
  'chooseLanguage': 'Choose Language',
  'arabic': 'Arabic',
  'english': 'English',
  'german': 'German',
  'easyCut': 'Easy Cut',
  'startWithUs': 'Start with us is very easy \nWe save your Time',
  'bookingNow': 'Booking Now',
  'bookAnyTime': 'Book any time. \nwe serve the nearest salon for you.',
  'trackReceipt': 'Track Receipment',
  'accessPayments':
      'You can now access your payments \nand have access to buy products.',
  'listProducts': 'List Products',
  'buyProducts': 'You can buy any product \n from your salon.',
  'continue': 'Continue',
  'welcome': 'Welcome',
  'happyToSeeYou': 'Happy to see you,',
  'loginNow': 'Login Now and Save your Time.',
  'email': 'Email',
  'password': 'Password',
  'forgetPassword': 'Forget Password?',
  'login': 'Login',
  'dontHaveAccount': "Don't have an account?",
  'register': 'Register',
  'resetPassword': 'Reset Password',
  'congratulation': 'Congratulation',
  'enterNewPassword': 'Please, Enter new Password',
  'reEnterPassword': 'Re-Enter Password',
  'goToLogin': 'Go to Login',
  'fullName': 'Full Name',
  'phoneNumber': 'Phone Number',
  'haveAnAccount': 'Have an account?',
  'gender': 'Gender',
  'male': 'Male',
  'female': 'Female',
  'nameNotValid': 'Name not valid',
  'emailNotValid': 'Email not valid',
  'phoneNotValid': 'Phone not valid',
  'requiredField':
      "This Field is required to access the data based on your information",
  'cantBeLessThan': "Can't be less than",
  'cantBeGreaterThan': "Can't be greater than",
  'alert': "Alert!",
  'exitApp': 'Do you want exit App?',
  'yes': 'Yes',
  'no': 'No',
  'Your salon is on your phone': 'Your salon is on your phone',
  'Near for you': 'Near for you',
  'Don’t waste your time and book at your preference':
      'Don’t waste your time and book at your preference',
  'Newest Salons': 'Newest Salons',
  'Please login first to choose among various barbers in your location':
      'Please login first to choose among various barbers in your location',
  'Hello': 'Hello',
  'All Bookings': 'All Bookings',
  'No bookings available': 'No bookings available',
  'Salon Name:': 'Salon Name:',
  'username': 'username :',
  'Salon Phone:': 'Salon Phone:',
  'Day': 'Day:',
  'Time:': 'Time:',
  'Total:': 'Total:',
  'Status:': 'Status:',
  'Delete Account': 'Delete Account',
  'About': 'About',
  'Favorites': 'Favorites',
  'Home': 'Home',
  'Booking': 'Booking',
  'Profile': 'Profile',
  'Are you sure want to exit the app?': 'Are you sure want to exit the app?',
  'Country': 'Country',
  'Select State': 'Select State',
  'Please select State': 'Please select State',
  'Select City': 'Select City',
  'Please select City': 'Please select City',
  'Select Image': 'Select Image',
  'Email is required': 'Email is required',
  'Please enter a valid Gmail address': 'Please enter a valid Gmail address',
  'check your mail': 'check your mail',
  'enter your mail please!': 'enter your mail please!',
  'Congratulation': 'Congratulation',
  'You information is correct \nWait for loading Data.':
      'You information is correct \nWait for loading Data.',
  'Your verify code is correct': 'Your verify code is correct',
  'Your code is incorrect': 'Your code is incorrect',
  'Warning': 'Warning',
  'Success': 'Success',
  'Congratulations, PIN is correct!': 'Congratulations, PIN is correct!',
  'Error': 'Error',
  'The PIN you entered is incorrect. Try again.':
      'The PIN you entered is incorrect. Try again.',
  'Please, choose a date': 'Please, choose a date',
  '"Please, choose a time"': '"Please, choose a time"',
  'Please, choose at least one service': 'Please, choose at least one service',
  'Booking Successful': 'Booking Successful',
  'Please wait until the salon accepts your booking':
      'Please wait until the salon accepts your booking',
  'Booking Error': 'Booking Error',
  'You already have a booking at this time. Please choose a different time or date.':
      'You already have a booking at this time. Please choose a different time or date.',
  'Your information is incorrect': 'Your information is incorrect',
  'Booking Now': 'Booking Now',
  'Booking Details': 'Booking Details',
  'Back to Home': 'Back to Home',
  'Your Booking is still not accepted, \n':
      'Your Booking is still not accepted',
  'You must upload image for your Profile':
      'You must upload image for your Profile',
  'Register Success': 'Register Success',
  'Your Register is successfully.Go to your account to get verify code':
      'Your Register is successfully.Go to your account to get verify code',
  'user_name': 'user name',
  'Create an Account to Show your profile': 'قم بإنشاء حساب لإظهار ملفك الشخصي',
  'To view or make bookings, you need to create an account and log in.':
      'To view or make bookings, you need to create an account and log in',
  'Create an Account to Access Bookings':
      'Create an Account to Access Bookings',
  'To view , you need to create an account and log in.':
      'To view , you need to create an account and log in.',
  'Submit': 'Submit',
  'Choose Services': 'Choose Services',
  'Choose': 'Choose',
  'Choose Time': 'Choose Time',
  'Choose Date': 'Choose Date',
  'Chair': 'Chair',
  'Choose Chair': 'Choose Chair',
  'Name': 'Name',
  'Book Now': 'Book Now',
  'Salon Name': 'Salon Name',
  'Date': 'Date',
  'Time': 'Time',
  'Duplicate Booking': 'Duplicate Booking',
  'is already booked at this time. Please choose a different chair, time, or date.':
      'is already booked at this time. Please choose a different chair, time, or date.',
  'Failed to save booking to API backend':
      'Failed to save booking to API backend',
  'Booking submission failed': 'Booking submission failed',
  'Added to your Favorites': 'Added to your Favorites',
  'There is no data': 'There is no data',
  'Removed from your Favorites': 'Removed from your Favorites',
  'Services': 'Services',
  'Products': 'Products',
  'Price:': 'Price:',
  'Number:': 'Number:',
  'Please check your internet connection':
      'Please check your internet connection',
  'Address': 'Address',
  'Logout': 'Logout',
  'Waiting': 'Waiting',
  'Accepted': 'Accepted',
  'Refused': 'Refused',
  'Exit': 'Exit',
  'Booking Approved': 'Booking Approved',
  'Your booking has been approved!': 'Your booking has been approved!',
  'Booking Refused': 'Booking Refused',
  'Your booking has been refused.': 'Your booking has been refused.',
  'No salons available.': 'No salons available.',
  'Are you sure to delete your account?':
      'Are you sure to delete your account?',
  'Failed to Delete Account, Try Again': 'Failed to Delete Account, Try Again',
  'There is no data for your country': 'There is no data for your country',
  'An error occurred while fetching data.':
      'An error occurred while fetching data.',
  'Action failed.': 'Action failed.',
  'Failed to perform action. Please try again.':
      'Failed to perform action. Please try again.',
  'No data available': 'No data available',
  'Failed to load data. Please try again.':
      'Failed to load data. Please try again.',
  'Email Already Exists': 'Email Already Exists',
  'egypt': 'egypt',
  'name': 'name',
  'Email Found': 'Email Found',
  'Please, Check your Account,We sent Verification code':
      'Please, Check your Account,We sent Verification code',
  'Email is not found': 'Email is not found',
  'Password Change Successfully': 'Password Change Successfully',
  'please choose a Strong Password': 'please choose a Strong Password',
  'New Password is not Equal to Confirm Password':
      'New Password is not Equal to Confirm Password',
  'Login Required': 'Login Required',
  'You need to log in to continue. Do you want to log in?':
      'You need to log in to continue. Do you want to log in?',
  'Log In': 'Log In',
  'Cancel': 'Cancel',
  'Please, Enter the verification code': 'Please, Enter the verification code',
  'Please, fill in the form': 'Please, fill in the form',
  'View Products': 'View Products',
  'Now you can buy products sold in the salon and add them to your bill':
      'Now you can buy products sold in the salon and add them to your bill',
  'Track invoice': 'Track invoice',
  'You can see how much your haircut will cost. Also, if you want to buy a product':
      'You can see how much your haircut will cost. Also, if you want to buy a product',
  'Now you can book at any time. We also provide you with the nearest salons to you':
      'Now you can book at any time. We also provide you with the nearest salons to you"',
  'Your start will be easier because we will save your time':
      'Your start will be easier because we will save your time',
  'Rating successfully': 'Rating successfully',
  'Total Price': 'Total Price',
  'Total Time': 'Total Time',
  'Start Time': 'Start Time',
  'min': 'min',
  'PM': 'PM',
  'AM': 'AM',
  'Men': 'Men',
  'Women': 'Women',
  'Search': 'Search',
  'Sorry': 'Sorry',
  'Salon is closed on this date': 'Salon is closed on this date',
  'Connection error': 'Connection error',
  'Search for a Salon or nearest city...':
      'Search for a Salon or nearest city...',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
};
