Map<String, String> langAr = {
  'chooseLanguage': 'اختر اللغه',
  'arabic': 'العربيه',
  'english': 'الانجليزيه',
  'german': 'الالمانيه',
  'easyCut': 'Easy Cut',
  'startWithUs': 'بدايتك هتكون اسهل \n لاننا هنحافظ علي وقتك',
  'bookingNow': 'حجز الميعاد',
  'bookAnyTime':
      'دلوقتي تقدر تحجز في اي وقت \n وكمان وفرنالك اقرب الصالونات ليك',
  'trackReceipt': 'تتبع الفاتوره',
  'accessPayments': 'تقدر تشوف حلقتك هتكلفك كام \n وكمان لو حابب تشتري منتج',
  'listProducts': 'عرض المنتجات',
  'buyProducts':
      'دلوقتي بقي ف امكانك انك تشتري \n منتجات بتتباع في الصالون وتضيفها لفاتورتك',
  'continue': 'التالي',
  'welcome': 'اهلا بك',
  'happyToSeeYou': 'نحن سعداء برؤيتك',
  'loginNow': 'سجل دخول الان وحافظ علي وقتك',
  'email': 'الايميل',
  'password': 'كلمه المرور',
  'forgetPassword': 'هل نسيت كلمه المرور؟',
  'login': 'دخول',
  'dontHaveAccount': 'ليس لديك حساب؟',
  'register': 'سجل الان',
  'resetPassword': 'إعادة تعيين كلمة المرور',
  'congratulation': 'تهانينا',
  'enterNewPassword': 'من فضلك، ادخل كلمه المرور الجديده',
  'reEnterPassword': 'اعاده كلمه المرور',
  'goToLogin': 'اذهب للدخول',
  'fullName': 'الاسم بالكامل',
  'phoneNumber': 'رقم الهاتف',
  'haveAnAccount': 'هل لديك حساب؟',
  'gender': 'النوع',
  'male': 'ذكر',
  'female': 'انثي',
  'nameNotValid': 'الاسم غير صحيح',
  'emailNotValid': 'الايميل غير صحيح',
  'phoneNotValid': 'رقم الهاتف غير صحيح',
  'requiredField': 'لا يمكن ان يكون فارغ',
  'cantBeLessThan': 'لا يمكن ان يكون اقل من',
  'cantBeGreaterThan': 'لا يمكن ان يكون اكبر من',
  'alert': 'تحذير',
  'exitApp': 'هل تريد الخروج من التطبيق؟',
  'yes': 'نعم',
  'no': 'لا',
  'Your salon is on your phone': 'صالونك على هاتفك',
  'Near for you': 'قريب منك',
  'Don’t waste your time and book at your preference':
      'لا تضيع وقتك واحجز حسب رغبتك',
  'Newest Salons': 'أحدث الصالونات',
  'Please login first to choose among various barbers in your location':
      'يرجى تسجيل الدخول أولاً للاختيار بين العديد من الحلاقين في منطقتك',
  'Hello': 'اهلا بك ',
  'All Bookings': 'جميع الحجوزات',
  'No bookings available': 'لا توجد حجوزات متاحة',
  'Salon Name': 'اسم الصالون ',
  'username': 'اسم العميل :',
  'Salon Phone:': ' موبايل  الصالون :',
  'Day': 'يوم',
  'Time:': 'الساعه :',
  'Total:': 'المبلغ :',
  'Status:': ' الحاله :',
  'Delete Account': 'حذف الحساب ',
  'About': 'عن ',
  'Favorites': 'المفضله',
  'Home': 'الصفحه الرئيسيه',
  'Booking': 'الحجز',
  'Profile': 'الحساب الشخصي',
  'Are you sure want to exit the app?':
      'هل أنت متأكد من رغبتك في الخروج من التطبيق؟',
  'Country': 'بلد',
  'Select State': 'إختر الولاية',
  'Please select State': 'الرجاء اختيار الولاية',
  'Select City': 'اختر المدينة',
  'Please select City': 'الرجاء اختيار المدينة',
  'Select Image': 'اختر صورة',
  'Email is required': 'البريد الإلكتروني مطلوب',
  'Please enter a valid Gmail address': 'الرجاء إدخال عنوان Gmail صحيح',
  'enter your mail please!': 'أدخل بريدك من فضلك!',
  'check your mail': 'تحقق من بريدك',
  'Congratulation': 'تهنئة',
  'You information is correct \nWait for loading Data.':
      'معلوماتك صحيحة انتظر تحميل البيانات.',
  'Your verify code is correct': 'رمز التحقق الخاص بك صحيح',
  'Your code is incorrect': 'الرمز الخاص بك غير صحيح',
  'Warning': 'تحذير',
  'Success': 'تم بنجاح ',
  'Congratulations, PIN is correct!': 'تهانينا ، رقم التعريف الشخصي صحيح!',
  'Error': 'خطأ',
  'The PIN you entered is incorrect. Try again.':
      'رقم التعريف الشخصي الذي أدخلته غير صحيح. حاول مرة أخرى.',
  'Please, choose a date': 'من فضلك اختر تاريخ',
  'Please, choose a time': 'من فضلك اختر الوقت"',
  'Please, choose at least one service': 'من فضلك، اختر خدمة واحدة على الأقل',
  'Booking Successful': 'تم الحجز بنجاح',
  'Please wait until the salon accepts your booking':
      'يرجى الانتظار حتى يقبل الصالون حجزك',
  'Booking Error': 'خطأ في الحجز',
  'You already have a booking at this time. Please choose a different time or date.':
      'لديك حجز بالفعل في هذا الوقت. يرجى اختيار وقت أو تاريخ آخر.',
  'Your information is incorrect': 'معلوماتك غير صحيحة',
  'Booking Now': 'الحجز الآن',
  'Booking Details': 'تفاصيل الحجز',
  'Back to Home': 'العودة إلى الصفحة الرئيسية',
  'Your Booking is still not accepted, \n': 'حجزك لم يتم قبوله بعد',
  'You must upload an image for your profile':
      'يجب عليك تحميل صورة لملفك الشخصي',
  'Register Success': 'تسجيل النجاح',
  'Your Register is successfully.Go to your account to get verify code':
      'تم تسجيلك بنجاح. انتقل إلى حسابك للحصول على رمز التحقق.',
  'user_name': 'اسم المستخدم',
  'Create an Account to Show your profile': 'قم بإنشاء حساب لإظهار ملفك الشخصي',
  'To view or make bookings, you need to create an account and log in.':
      'لعرض أو إجراء الحجوزات، يجب عليك إنشاء حساب وتسجيل الدخول.',
  'Create an Account to Access Bookings': 'إنشاء حساب للوصول إلى الحجوزات',
  'To view , you need to create an account and log in.':
      'لعرضها، يجب عليك إنشاء حساب وتسجيل الدخول.',
  'Submit': 'يُقدِّم',
  'Choose Services': 'اختر الخدمات',
  'Choose': 'يختار',
  'Choose Time': 'اختر الوقت',
  'Choose Date': 'اختر التاريخ',
  'Chair': 'كرسي',
  'Choose Chair': 'اختر الكرسي',
  'Name': 'الاسم ',
  'Book Now': 'احجز الآن',
  // ignore: equal_keys_in_map
  'Salon Name': 'اسم الصالون',
  'Date': 'تاريخ',
  'Time': 'وقت',
  'Duplicate Booking': 'حجز مكرر',
  'is already booked at this time. Please choose a different chair, time, or date.':
      'تم حجز الموعد بالفعل في هذا الوقت. يرجى اختيار مقعد أو وقت أو تاريخ مختلف.',
  'Failed to save booking to API backend':
      'فشل حفظ الحجز في واجهة برمجة التطبيقات الخلفية',
  'Booking submission failed': 'فشل إرسال الحجز',
  'Added to your Favorites': 'تمت إضافته إلى المفضلة لديك',
  'There is no data': 'لا يوجد بيانات',
  'Removed from your Favorites': 'تمت الإزالة من المفضلة لديك',
  'Services': 'خدمات',
  'Products': 'منتجات',
  'Price:': ' سعر:  ',
  'Number:': 'رقم:',
  'Please check your internet connection': 'يرجى التحقق من اتصالك بالإنترنت',
  'Address': 'عنوان',
  'Logout': 'تسجيل الخروج',
  'Waiting': 'منتظر',
  'Accepted': 'مقبول',
  'Refused': 'رفض',
  'Exit': 'خروج',
  'Booking Approved': 'تمت الموافقة على الحجز',
  'Your booking has been approved!': 'لقد تمت الموافقة على حجزك',
  'Booking Refused': 'تم رفض الحجز',
  'Your booking has been refused.': 'لقد تم رفض الحجز الخاص بك',
  'No salons available.': 'لا يوجد صالونات متاحة.',
  'Are you sure to delete your account?': 'هل أنت متأكد من حذف حسابك؟',
  'Failed to Delete Account, Try Again': 'فشل حذف الحساب، حاول مرة أخرى',
  'There is no data for your country': 'لا توجد بيانات لبلدك',
  'Action failed.': 'فشل الإجراء.',
  'Failed to perform action. Please try again.':
      'فشل تنفيذ الإجراء. يرجى المحاولة مرة أخرى.',
  'No data available': 'لا توجد بيانات متاحة',
  'Failed to load data. Please try again.':
      'فشل تحميل البيانات. يرجى المحاولة مرة أخرى.',
  'Email Already Exists': 'البريد الإلكتروني موجود بالفعل',
  'egypt': 'مصر',
  'name': 'hsl',
  'Email Found': 'تم العثور على البريد الإلكتروني',
  'Please, Check your Account,We sent Verification code':
      'من فضلك، تحقق من حسابك، لقد أرسلنا رمز التحقق',
  'Email is not found': 'لم يتم العثور على البريد الإلكتروني',
  'Password Change Successfully': 'تم تغيير كلمة المرور بنجاح',
  'please choose a Strong Password': 'الرجاء اختيار كلمة مرور قوية',
  'New Password is not Equal to Confirm Password':
      'كلمة المرور الجديدة لا تساوي تأكيد كلمة المرور',
  'Login Required': 'تسجيل الدخول مطلوب',
  'You need to log in to continue. Do you want to log in?':
      'تحتاج إلى تسجيل الدخول للمتابعة. هل تريد تسجيل الدخول؟',
  'Log In': 'تسجيل الدخول',
  'Cancel': 'إلغاء الأمر',
  'Please, Enter the verification code': 'من فضلك أدخل رمز التحقق',
  'Please, fill in the form': 'من فضلك قم بملء النموذج',
  'View Products': 'عرض المنتجات',
  'Now you can buy products sold in the salon and add them to your bill':
      'الآن يمكنك شراء المنتجات المباعة في الصالون وإضافتها إلى فاتورتك',
  'Track invoice': 'تتبع الفاتورة',
  'You can see how much your haircut will cost. Also, if you want to buy a product':
      'يمكنك معرفة تكلفة قص شعرك. أيضًا، إذا كنت ترغب في شراء منتج',
  'Now you can book at any time. We also provide you with the nearest salons to you':
      'الآن يمكنك الحجز في أي وقت، كما نوفر لك أقرب الصالونات إليك',
  'Your start will be easier because we will save your time':
      'ستكون بدايتك أسهل لأننا سنوفر لك الوقت',
  'Rating successfully': 'Rating successfully',
  'Total Price': 'السعر الاجمالي',
  'Total Time': 'الوقت الإجمالي',
  'Start Time': 'وقت البدء',
  'min': 'دقيقة',
  'PM': 'مساءً',
  'AM': 'صباحا',
  'Men': 'رجال',
  'Women': 'نساء',
  'Search': 'بحث',
  'Sorry': 'ناسف',
  'Salon is closed on this date': 'الصالون مغلق في هذا التاريخ',
  'Connection error': 'خطأ في الاتصال'
};
